# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '9.0'
target 'Firebase' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn'
  pod 'FBSDKShareKit'
  
  target 'Firebase-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Firebase-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Firebase-tvOS

end
